logging:
  level:
    com:
      dmq:
       sample:
        mapper: debug
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1/test?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    hikari:
      idle-timeout: 5000
      connection-timeout: 5000
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database: 0
dm:
  config:
    async-tables: user,t_order_1
    redis-address: redis://127.0.0.1:6379
    expire-seconds: -1

